spring.application.name=banking-portal
server.servlet.context-path=/

# Target our local MySQL Instance 
spring.datasource.url=jdbc:mysql://localhost:3306/bankapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=bankuser
spring.datasource.password=BankPass123!

# JPA Translation Layer
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
